apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  annotations:
  labels:
    role: registry
    app: {{ include "cytomine.name" . }}
    component: {{ .Release.Name }}-registry
    release: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: registry
  selector:
    matchLabels:
      app: registry
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: registry
        app: registry
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: temp
          emptyDir: {}
      containers:
        - name: registry
          image: registry:2.8.3
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          volumeMounts:
            - name: temp
              mountPath: /data
          ports:
            - name: registry
              containerPort: 5000
              protocol: TCP

