{{ if .Values.pims.deploy }}
{{- $imageStorageClassName := .Values.pims.imageStorage.storageClassName | required ".Values.pims.imageStorage.storageClassName" -}}
{{- $tempImageStorageClassName := .Values.pims.tempImageStorage.storageClassName | required ".Values.pims.tempImageStorage.storageClassName is required." -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cytomine.name" . }}-pims
  annotations:
    kube-score/ignore: pod-probes,container-security-context-user-group-id
  labels:
    role: pims
    app: {{ include "cytomine.name" . }}
    component: {{ .Release.Name }}-pims
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-pims
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: pims
        app: {{ template "cytomine.name" . }}-pims
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.containerSecurity.userID }}
        fsGroup: {{ .Values.containerSecurity.fsgroupID }}
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: pims-logging
          configMap:
            name: {{ template "cytomine.name" . }}-pims-logging
        - name: temp
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}-pims
          image: "{{ .Values.images.pims }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          envFrom:
            - configMapRef:
                name: cytomine-pims-config
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cytomine.name" . }}-postgresql-secret
                  key: password
            - name: CYTOMINE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cytomine.name" . }}-pims-secret
                  key: public_key
            - name: CYTOMINE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cytomine.name" . }}-pims-secret
                  key: private_key
          volumeMounts:
            - name: images
              mountPath: "/data/images"
            - name: images
              mountPath: "/data/pims"
            - name: image-temp
              mountPath: "/tmp/uploaded"
            - name: pims-logging
              mountPath: /cm_configs/app/logging.yml
              subPath: logging.yml
            - name: temp
              mountPath: /tmp
            - name: temp
              mountPath: /app
          ports:
            - name: http
              containerPort: {{ .Values.pims.port }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containerSecurity.allowPrivilegeEscalation }}
            privileged: {{ .Values.containerSecurity.privileged }}
            readOnlyRootFilesystem: {{ .Values.containerSecurity.readOnlyRootFilesystem }}
          resources:
            {{- toYaml .Values.pims.resources | nindent 12 }}
      initContainers:
        - name: {{ .Chart.Name }}-pims-init
          image: "{{ .Values.images.pims }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containerSecurity.allowPrivilegeEscalation }}
            privileged: {{ .Values.containerSecurity.privileged }}
            readOnlyRootFilesystem: {{ .Values.containerSecurity.readOnlyRootFilesystem }}
          command:
            - /bin/bash
            - -c
            - >
              set -x;
              cp -r /app/* /fix/;
          volumeMounts:
            - name: temp
              mountPath: /fix/
          resources:
            {{- toYaml .Values.pims.resources | nindent 12 }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: image-claim
      spec:
        storageClassName: {{ $imageStorageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.imageStorage }}
    - metadata:
        name: temp-image-claim
      spec:
        storageClassName: {{ $tempImageStorageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.tempImageStorage }}
{{ end }}
