apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-engine
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: app-engine-sa
  annotations:
    kubernetes.io/service-account.name: app-engine

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # we need to restrict that by namespace (Role not ClusterRole)
metadata:
  name: pod-starter
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["post","get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-starter-app-engine

subjects:
- kind: ServiceAccount
  name: app-engine
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: pod-starter # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""
