apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: core
  annotations:
    # https://stackoverflow.com/a/73548785
    # It seems that we are using k8s official nginx image.
    # not sure, though
    nginx.ingress.kubernetes.io/proxy-body-size: 20Gi
    nginx.org/client-max-body-size: 20Gi
    #
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-error-log: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ include "pims.url" . }}, {{ include "core.url" . }}, {{ include "upload.url" . }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,dateFull,content-type-full
    nginx.org/proxy-connect-timeout: 3600s
    nginx.org/proxy-read-timeout: 3600s
    nginx.org/proxy-send-timeout: 3600s
    cert-manager.io/issuer: letsencrypt
spec:
  ingressClassName: public
  rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
          - path: /server
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-core
                port:
                  number: {{ .Values.core.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-core
                port:
                  number: {{ .Values.core.port }}
          - path: /iam
            pathType: Prefix
            backend:
              service:
                name: iam
                port:
                  number: {{ .Values.iam.port }}
          - path: /cbir
            pathType: Prefix
            backend:
              service:
                name: cbir
                port:
                  number: {{ .Values.cbir.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-web-ui
                port:
                  number: {{ .Values.web_ui.port }}
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-pims
                port:
                  number: {{ .Values.pims.port }}
          - path: /pims
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-pims
                port:
                  number: {{ .Values.pims.port }}
  tls:
  - hosts:
    - {{ include "core.hostname" . }}
    secretName: {{ include "cytomine.name" . }}-ingress-tls-1

