apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cytomine.name" . }}-ingress-{{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-error-log: "true"
    nginx.org/proxy-connect-timeout: 3600s
    nginx.org/proxy-read-timeout: 3600s
    nginx.org/proxy-send-timeout: 3600s
spec:
  rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
          - path: /server
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-core
                port:
                  number: {{ .Values.core.port }}
          # - path: /nginx
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: {{ include "cytomine.name" . }}-nginx
          #       port:
          #         number: {{ .Values.nginx.port }}
    - host: {{ .Values.global.urlUpload }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-nginx
                port:
                  number: {{ .Values.nginx.port }}
    - host: {{ .Values.global.imsDomainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-nginx
                port:
                  number: {{ .Values.nginx.port }}
  {{ if .Values.global.use_tls }}
  tls:
  - hosts:
    - {{ .Values.global.domainName }}
    - {{ .Values.global.urlUpload }}
    - {{ .Values.global.imsDomainName }}
    secretName: {{ include "cytomine.name" . }}-ingress-tls
  {{ end }}
