apiVersion: v1
kind: Service
metadata:
  name: iam
spec:
  clusterIP: None
  selector:
    app: postgres-iam
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      protocol: TCP
