apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  labels:
    app: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
      - name: iam
        image: "{{ .Values.images.iam }}"
        ports:
        - containerPort: {{ .Values.iam.port }}
        envFrom:
        - configMapRef:
            name: iam
        - secretRef:
            name: {{ include "cytomine.name" . }}-postgresql-secret
