name: Docker push Helm package

on:
  push:
    # branches:
    #   - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        run: |
          echo "CHART_VERSION=$(cat ./charts/cytomine/Chart.yaml | grep "version:" | sed -E 's/^version: (.*)$/\1/g')" >> $GITHUB_ENV

      - name: Get version
        run: echo ${{ env.CHART_VERSION }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm package
        run: helm package ./charts/cytomine


      - name: Helm login
        run: helm registry login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} registry-1.docker.io


      # - name: Build and push Docker image
      #   id: push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ${{ matrix.image.context || matrix.image.name }}
      #     file: ./${{ matrix.image.dockerfile_location || matrix.image.context || matrix.image.name }}/Dockerfile
      #     push: true
      #     tags: cytomine/${{ matrix.image.name }}
      #     labels: latest
      #     allow: network.host
      #     network: host
